### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'total')

### ISSUE THREAD

**Issue by binhodev** [singhbhaskar/AdminWrite#1]
Hi, after install packages and run the project i got this error:

```
VITE v4.2.1  ready in 2167 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
07:11:40 [vite-plugin-svelte] ssr compile in progress ...
Sourcemap for "C:/Projetos/AdminWrite/node_modules/@appwrite.io/pink/dist/pink.css" points to missing source files
TypeError: Cannot read properties of null (reading 'total')
    at +page.svelte:26:70
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1997:22)      
    at Object.default (root.svelte:69:41)
    at eval (/src/routes/+layout.svelte:60:33)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1997:22)      
    at root.svelte:45:39
    at $$render (/node_modules/svelte/internal/index.mjs:1997:22)
    at Object.render (/node_modules/svelte/internal/index.mjs:2005:26)        
    at Module.render_response (/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:180:29)
    at async Module.render_page (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:285:10)
TypeError: Cannot read properties of null (reading 'total')
    at +page.svelte:26:70
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1997:22)      
    at Object.default (root.svelte:69:41)
    at eval (/src/routes/+layout.svelte:60:33)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1997:22)      
    at root.svelte:45:39
    at $$render (/node_modules/svelte/internal/index.mjs:1997:22)
    at Object.render (/node_modules/svelte/internal/index.mjs:2005:26)        
    at Module.render_response (/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:180:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by singhbhaskar** [comment]
Hi @silvinhofranca,
Thanks for raising the issue. Can you in your node modules is appwrite pink downloaded?

Also try to run 'npm install' once it should install all the dependencies.

**Comment by singhbhaskar** [comment]
Did the `npm install` solved the issue? Let me know so that I can close this issue.

**Comment by singhbhaskar** [comment]
Closing this as there's no response
